### ISSUE TITLE
File extension change request

### ISSUE THREAD

**Issue by dmytrokosiachenko** [mbonig/state-machine#20]
For convenient usage in Visual Studio Code [there is a suggestion](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html) from AWS to use *.json.asl file extension. Currently with *.workflow.json extension Visual Studio Code can not define it automatically correctly as ASL file.

**Comment by mbonig** [comment]
Thanks for the suggestion! I've created a PR that allows you to provide your own extension to use with a predefined extension (AWS_RECOMMENDED_JSON_EXT). Let me know what you think.
