### ISSUE TITLE
Set projen peerDeps using ">="

### ISSUE THREAD

**Issue by rogerchi** [mbonig/state-machine#27]
I'm seeing these warnings when using this construct in a projen managed project:
```
warning " > @matthewbonig/state-machine@0.0.26" has incorrect peer dependency "projen@^0.65.74".
```

Also, I get type mismatches when trying to use the `StepFunctionsAutoDiscover` integration.

I think the peerDep for projen should be specified like `projen@>=0.65.74` to allow newer minor versions of projen.

https://github.com/mbonig/state-machine/blob/771882602949317a0427c412cc27157e169a491d/.projenrc.ts#L15

**Comment by mbonig** [comment]
@rogerchi thanks! I've made some updates that should resolve this.
