### ISSUE TITLE
projen mistakenly as (non dev)dependency

### ISSUE THREAD

**Issue by WtfJoke** [mbonig/state-machine#33]
Hi there

We thought about using your construct as it seemed to fit our needs (for replacing account related hardcoded ids in our step function), thanks for creating it :)

However, currently `projen` is listed as dependency in https://github.com/mbonig/state-machine/blob/db5ecb392ba9106a4357813f571efce8f2e76542/package.json#L69  
Probably thats only added by mistake as consumers should'nt need this dependency when using this construct.

**Comment by mbonig** [comment]
Projen is required because I leverage the auto-discoverability pieces for this:

https://github.com/mbonig/state-machine/blob/main/API.md#stepfunctionsautodiscover-

**Comment by WtfJoke** [comment]
Ah I see, then I'll close this :)
