### ISSUE TITLE
StateMachineProps.definition has been deprecated

### ISSUE THREAD

**Issue by mncoldsmoke** [mbonig/state-machine#38]
When synth'ing the CDK I get:
[WARNING] aws-cdk-lib.aws_stepfunctions.StateMachineProps#definition is deprecated.
  use definitionBody: DefinitionBody.fromChainable()
  This API will be removed in the next major release.

**Comment by mbonig** [comment]
Can you confirm what version you're using? I thought I had gotten that cleared up and I'm not using `definition` anywhere anymore.

**Comment by mncoldsmoke** [comment]
Sorry, I updated the WRONG package.json, package-lock.json files. 
Version 0.0.33 works fine if you are actually using it.

**Comment by ebisbe** [comment]
Mine is "@matthewbonig/state-machine": "^0.0.36", and for me the issue is with the typescript definitions in here https://github.com/mbonig/state-machine/blob/f2a50a849b37e85e7cde80f5bdd9465b83727bd3/src/StateMachine.ts#L23 

```
error TS2561: Object literal may only specify known properties, but 'definitionBody' does not exist in type 'StateMachineProps'. Did you mean to write 'definition'?

141       definitionBody: stepfunctions.DefinitionBody.fromFile(definitionPath),
```

**Comment by ebisbe** [comment]
So after a little of digging I found out that when using the autodiscover it generates the new statematchine based on the properties you defined in https://github.com/mbonig/state-machine/blob/f2a50a849b37e85e7cde80f5bdd9465b83727bd3/src/StateMachine.ts#L23 and it's not throwing any error but if you use your state machine without the autodiscover then it will throw the error. 

Below there are the definitions from state machine. I'm not sure what is the best solution but I'm pretty sure once it gets removed the issue will surface again. 
```
/**
     * Definition for this state machine
     * @deprecated use definitionBody: DefinitionBody.fromChainable()
     */
    readonly definition?: IChainable;
    /**
     * Definition for this state machine
     */
    readonly definitionBody?: DefinitionBody;
```
